# key notes 

## data sources:
1. reddit scraping while possible is probably too noisey to be useful

2. yahoo scraping can be done by scraping the wayback machine recursively use the article tag with role=article (the rss vertion of it dosent have enough saves in waybckmachine)

3. wikipedia scraping is very clean data but unfortunatly there isnt alot of changes so we are again data fin

## train strategy 
###### 1. seperate data into diffrent segments based on how frequantly it gets updated 
2. make a nested training loop that updates based on that frequncy. (this helps preventing needles recalculations)
3. use an lstm on the price data that is prompted with extra information from the other segments

In [97]:
import tensorflow as tf
import numpy as np
import random 

4

In [137]:
#toy unbatched exmple
tf.config.run_functions_eagerly(False)
N=3
big=tf.data.Dataset.range(N)
r=tf.data.Dataset.random().map(lambda x: 4+x%20).take(N)
small=tf.data.Dataset.zip((big,r))
small=small.map(lambda x,r:tf.range(x,x+r))
small=small.map(lambda x:tf.data.Dataset.from_tensor_slices(x).batch(4)).prefetch(tf.data.AUTOTUNE)
for elem in small:
    #big loop updates HERE
    print(f"len={len(elem)}")
    for x in elem:
        #small loop updates HERE 
        print(x)
tf.config.run_functions_eagerly(True)

len=3
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([4 5 6 7], shape=(4,), dtype=int64)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int64)
len=5
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int64)
tf.Tensor([ 9 10 11 12], shape=(4,), dtype=int64)
tf.Tensor([13 14 15 16], shape=(4,), dtype=int64)
tf.Tensor([17], shape=(1,), dtype=int64)
len=4
tf.Tensor([2 3 4 5], shape=(4,), dtype=int64)
tf.Tensor([6 7 8 9], shape=(4,), dtype=int64)
tf.Tensor([10 11 12 13], shape=(4,), dtype=int64)
tf.Tensor([14], shape=(1,), dtype=int64)


In [129]:
tf.data.Dataset.random().take(1).get_single_element()

<tf.Tensor: shape=(), dtype=int64, numpy=226177639>